version: '3.8'
services:
  mysql_db_container:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./tmpdb:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
  redis_container:
    image: docker.io/bitnami/redis:7.4
    environment:
      - REDIS_PASSWORD=redis12task
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/bitnami/redis/data
